# Задание
Дана целочисленная прямоугольная матрица. Определить количество столбцов, не
содержащих ни одного нулевого элемента. Характеристикой строки целочисленной матрицы
назовем сумму ее положительных четных элементов. Переставляя строки заданной
матрицы, расположить их в соответствии с ростом характеристик.

In [1]:
import numpy as np

Создаем исходную матрицу

In [5]:
matrix = np.random.randint(-10, 10,(7, 10))
matrix

array([[  8,   7,  -3,   7,  -2,   8,   7, -10,  -5,  -6],
       [ -5,  -1,   9, -10,  -8,   1,  -8,   6,  -1,   4],
       [  6,   9,   3,   8,   9,  -2,  -4, -10,  -2,   7],
       [ -4,  -7,  -9,   1,   7,   3,   1,   7,  -9,   0],
       [  9,  -5,  -1,  -3,  -9,  -9,   5,   8,  -9,  -3],
       [ -4,   1,   1,  -7,   3,   2,  -1,   0,   4, -10],
       [ -6,   6,  -8,   4,  -4,  -6,  -2,   3,  -2, -10]])

Вычисляем характеристику каждой строки матрицы

In [7]:
row_sum = np.sum((matrix > 0) & (matrix % 2 == 0), axis=1)
row_sum

array([2, 2, 2, 0, 1, 2, 2])

Находим индексы строк, содержащих положительные четные элементы

In [9]:
non_zero_rows = np.flatnonzero(row_sum)
non_zero_rows

array([0, 1, 2, 4, 5, 6], dtype=int64)

Создаем новую матрицу, содержащую только строки, которые содержат положительные четные элементы,
и сортируем ее в порядке возрастания характеристик

In [11]:
new_matrix = matrix[non_zero_rows]
sorted_indices = np.argsort(row_sum[non_zero_rows])
sorted_matrix = new_matrix[sorted_indices]
sorted_matrix

array([[  9,  -5,  -1,  -3,  -9,  -9,   5,   8,  -9,  -3],
       [  8,   7,  -3,   7,  -2,   8,   7, -10,  -5,  -6],
       [ -5,  -1,   9, -10,  -8,   1,  -8,   6,  -1,   4],
       [  6,   9,   3,   8,   9,  -2,  -4, -10,  -2,   7],
       [ -4,   1,   1,  -7,   3,   2,  -1,   0,   4, -10],
       [ -6,   6,  -8,   4,  -4,  -6,  -2,   3,  -2, -10]])

Находим количество столбцов, не содержащих ни одного нулевого элемента, и возвращаем его

In [12]:
non_zero_columns = np.sum(np.count_nonzero(matrix, axis=0) == matrix.shape[0])
print(non_zero_columns)

8
