# Лабораторная работа 3.2. Домашнее задание

### Задание №1

Создайте два массива: в первом должны быть четные числа от 2 до 12 включительно, а в другом числа 7, 11, 15, 18, 23, 29.

$1.$ Сложите массивы и возведите элементы получившегося массива в квадрат:

In [1]:
import numpy as np

In [2]:
a = np.arange(2, 13, 2)
b = np.array([7, 11, 15, 18, 23, 29])
print(a + b)
print((a + b) ** 2)

[ 9 15 21 26 33 41]
[  81  225  441  676 1089 1681]


$2.$ Выведите все элементы из первого массива, индексы которых соответствуют индексам тех элементов второго массива, которые больше 12 и дают остаток 3 при делении на 5.

In [3]:
print(a[np.logical_and(b > 12, b % 5 == 3)])

[ 8 10]


*3.* Проверьте условие "Элементы первого массива делятся на 4, элементы второго массива меньше 14". (Подсказка: в результате должен получиться массив с True и False)

In [4]:
c = np.logical_and(a % 4 == 0, b < 14)
c

array([False,  True, False, False, False, False])

### Задание №2

* Найдите интересный для вас датасет. Например, можно выбрать датасет тут. http://data.un.org/Explorer.aspx (выбираете датасет, жмете на view data, потом download, выбирайте csv формат)
* Рассчитайте подходящие описательные статистики для признаков объектов в выбранном датасете
* Проанализируйте и прокомментируйте содержательно получившиеся результаты
* Все комментарии оформляйте строго в ячейках формата markdown
    

In [5]:
import csv
import numpy as np

In [7]:
with open('organizations_gdp_hist.csv', 'r', newline='') as csvfile:
    data = csv.reader(csvfile, delimiter=',')
    total = []
    gdp_variation = []
    for row in data:
        if row[4] == "Ingreso mediano alto":
            total.append(float(row[6]))
            gdp_variation.append(float(row[8]))

In [8]:
arr_t = np.array(total)
arr_v = np.array(gdp_variation)

In [9]:
print(f"Среднее значение ВВП в Ингресо медиано альт: {np.mean(arr_t)}")
print(f"Среднее значение изменения ВВП: {np.mean(arr_v)}")

Среднее значение ВВП в Ингресо медиано альт: 1531038886.3048372
Среднее значение изменения ВВП: 0.9125664043340592


In [10]:
print(f"Минимальное значение ВВП в Ингресо медиано альт: {np.min(arr_t)}")
print(f"Минимальное значение изменения ВВП: {np.min(arr_v)}")

Минимальное значение ВВП в Ингресо медиано альт: 0.0
Минимальное значение изменения ВВП: -5.34027530229791


In [11]:
print(f"Максимальное значение ВВП в Ингресо медиано альт: {np.max(arr_t)}")
print(f"Максимальное значение изменения ВВП: {np.max(arr_v)}")

Максимальное значение ВВП в Ингресо медиано альт: 9412034299.23122
Максимальное значение изменения ВВП: 10.7456116066371
