# Самостоятельное задание

###### Условие:
У нас есть данные о температуре воздуха в разные дни года в трех регионах: А, Б и В. Необходимо оценить, как меняется температура воздуха в каждом из этих регионов в зависимости от времени года. Для этого необходимо произвести анализ главных компонент.

#### Решение:

Для решения этой задачи можно воспользоваться методом анализа главных компонент (PCA). 

Сначала создадим матрицу данных Х, которая будет содержать данные о температуре воздуха в разные дни года в разных регионах.

In [13]:
import numpy as np

In [14]:
temperatures = np.array([[12, 10, 8, 14, 16, 20, 22, 24, 18, 16, 14, 12],
                         [28, 26, 24, 22, 20, 18, 16, 18, 20, 22, 24, 26],
                         [14, 12, 10, 8, 6, 4, 6, 8, 10, 12, 14, 16]])
X = temperatures.T

Затем вычислим матрицу ковариации С, использовуем метод np.linalg.eig, чтобы найти собственные значения и собственные векторы матрицы ковариации C, которые будут использоваться для определения главных компонент.

In [18]:
C = np.cov(X.T)
eigenvalues, eigenvectors = np.linalg.eig(C)

После этого сортируем собственные значения в порядке убывания и применяем метод np.dot для проектирования данных на новое пространство, определенное главными компонентами.

In [19]:
sort_order = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sort_order]
eigenvectors = eigenvectors[:, sort_order]

Y = np.dot(X, eigenvectors)

In [20]:
print("Собственные значения: ", eigenvalues)
print("Собственные векторы: \n", eigenvectors)
print("Новые данные: \n", Y)

Собственные значения:  [43.33734119  6.83787829  0.82478053]
Собственные векторы: 
 [[-0.68869971  0.62844589 -0.36159159]
 [ 0.55071068  0.12902077 -0.82466441]
 [ 0.47160413  0.76707849  0.43494843]]
Новые данные: 
 [[ 13.75796028  21.89303105 -21.34042456]
 [ 13.09073008  18.84394076 -19.83780942]
 [ 12.42349989  15.79485047 -18.33519427]
 [  6.246672    17.77332726 -19.72531183]
 [  2.82464296  17.23802051 -19.66906304]
 [ -1.9747855   17.95960553 -20.33599743]
 [ -3.51039802  20.49261274 -18.53995493]
 [ -2.84316783  23.54170303 -20.04257007]
 [  3.33366006  21.56322624 -18.65245251]
 [  6.7556891   22.09853299 -18.7087013 ]
 [ 10.17771814  22.63383974 -18.76495009]
 [ 13.59974718  23.16914649 -18.82119888]]


В результате выполнения этого кода мы получили собственные значения и собственные векторы матрицы ковариации, а также новые данные, проектированные на новое пространство, определенное главными компонентами.